---
title: "FIN 452 Dynamic Portfolio"
format: 
  html:
    embed-resources: true
editor: visual
---

## 

```{r, include = FALSE}

library(tidyverse)
library(rlang)
library(quantmod)
library(tidyquant)
library(lubridate)
library(gt)

```

### Data Wrangling

```{r, include = FALSE}

tickers <- c("NVDA", "XOM", "AMZN", "WM")  # Example tickers in various industries
weights <- c(0.25, 0.25, 0.25, 0.25)  # Corresponding weights
initial_portfolio_value <- 100000    # Starting portfolio value
start_date = "2015-01-30"
end_date = rollback(Sys.Date(), roll_to_first = FALSE) # returns the last day of the prior month


weights_df <- tibble::tibble(symbol = tickers,
                             weight = weights)%>%
  dplyr::arrange(symbol)


long_df <- tidyquant::tq_get(tickers,
                  get = "stock.prices",
                  from = start_date,
                  to = end_date)%>%
  dplyr::select(symbol, date, open, close)%>%
  dplyr::group_by(symbol) %>% 
  dplyr::arrange(symbol, date)%>%
  dplyr::mutate(log_cc = log(close/lag(close)),
                
                log_oc = log(close/open),
                
                log_co = log(open/lag(close)),
                
                event = ifelse(lubridate::day(date) < lubridate::day(lag(date)),
                               1, ifelse(lead(day(date)) < day(date),2,0)),
                ret = ifelse(event == 1, log_cc, 
                             ifelse(event == 2, log_co, log_cc))
                )


#Portfolio value returns must be the weighted sum of returns of individual stocks within the portfolio. If NVDA is weighted .75 and returns 1% and XOM is .25 and returns -1%, the portfolio return should be 0.5%


wide_df <- long_df %>%
  dplyr::mutate(ym = lubridate::format_ISO8601(date, precision = "ym")) %>%
  dplyr::select(symbol, ym, ret) %>% 
  dplyr::group_by(symbol, ym) %>% 
  dplyr::summarise(ret = sum(ret, na.rm = TRUE)) %>% 
  tidyr::pivot_wider(names_from = symbol,
                     values_from = ret,
                     names_prefix = "ret.") %>%
  drop_na() %>% 
  dplyr::mutate(port_ret = NA
                  ) 
 


for(i in 1:nrow(wide_df)){
  
 tmp_value <- 0
  
  if(i == 1){
    wide_df$port_ret[i] <- 0
    
  }else{
    
    for(j in 1:length(select(wide_df, starts_with("ret.")))){
      
     loop_symbol <-  wide_df %>% 
        select(starts_with("ret.")) %>% 
        rename_all(~stringr::str_replace(., "^ret.", "")) %>% 
        names(.)%>%
       .[j]
        
      weight_index <- match(loop_symbol, weights_df$symbol)
      
      col_char <- paste0("ret.", loop_symbol)
      
      loop_weight <- weights_df$weight[weight_index]
      
      tmp_ret <- wide_df[[col_char]][i]
      
      tmp_value <- tmp_value + loop_weight*tmp_ret
      
    }
      
    wide_df$port_ret[i] <- tmp_value 
    
  }
  
  

}


wide_df <- wide_df %>%
  dplyr::mutate(cumul_ret = cumsum(port_ret),
                port_value = initial_portfolio_value + initial_portfolio_value*cumul_ret)


event_ids <- long_df %>% 
  dplyr::filter(event == 1) %>% 
  dplyr::mutate(ym = lubridate::format_ISO8601(date, precision = "ym")) %>% 
  dplyr::select(symbol, ym, open) %>% 
  pivot_wider(names_from = symbol,
              values_from = open,
              names_prefix = "open.")





wide_df <- wide_df %>% 
  dplyr::left_join(event_ids, by = join_by( ym)) 



#With YYYY-MM specified, we can summarize returns by month at the end of our process

```

```{r, include = FALSE}

# At this point, I want the code to create a new column for each ticker to show allocation amounts in dollars. We can also show transactions for each ticker if its all done in the same for loop.


wide_df <- wide_df %>% 
  dplyr::mutate(
    across(.cols = starts_with("ret."),
           .fns = ~NA,
           .names = "{.col}_value_open") %>% 
      rename_all(~stringr::str_replace(., "^ret.", "")),
    
    across(.cols = starts_with("ret."),
           .fns = ~NA,
           .names = "{.col}_alloc") %>% 
      rename_all(~stringr::str_replace(., "^ret.", "")),
    
    across(.cols = starts_with("ret."),
           .fns = ~NA,
           .names = "{.col}_transaction") %>% 
      rename_all(~stringr::str_replace(., "^ret.", ""))
    
    )


for(i in 1:nrow(wide_df)){
  
  
  for(j in 1:length(tickers)){
    
    weight_index <- match(tickers[j], weights_df$symbol)
    
    loop_weight <- weights_df$weight[weight_index]
    
    loop_ret_col <- paste0("ret.", tickers[j], "")
    
    
    
    loop_ret <- wide_df[[loop_ret_col]][i] 
      
    
    
    col_name <- paste0(tickers[j], "_value_open", "")
    
    col_name_alloc <- paste0(tickers[j], "_alloc", "")
    
    col_name_trans <- paste0(tickers[j], "_transaction", "")
    
    stock_val <- ifelse(i == 1, loop_weight * wide_df$port_value[i], wide_df$port_value[i-1] * loop_weight)*(1+loop_ret)
    
    stock_val_close <- loop_weight*wide_df$port_value[i]
    
    wide_df[[col_name]][i] <- stock_val
    
    wide_df[[col_name_alloc]][i] <- stock_val_close
    
    wide_df[[col_name_trans]][i] <- stock_val_close - stock_val
    
  }
  
  
}







```

```{r, echo = FALSE}

wide_df %>% 
  dplyr::select("Date" = ym,
                starts_with("ret."),
                port_value,
                tidyselect::ends_with("_alloc"),
                tidyselect::ends_with("_transaction")) %>%
  dplyr::mutate(across(-c(Date, starts_with("ret.")), ~round(.x, digits = 0))) %>% 
  gt() %>% 
  tab_header(., title = "Desired Output") %>% 
  tab_style(style = cell_text(align = "center"),
            locations = cells_title("title"))
  



```
